/**
 * 用途：
 * - 逐表定义运行时状态集合到 Postgres schema 的映射配置。
 * - 播种规则、列映射和表预期集中在这里，让仓库层代码保持通用。
 */

function config(definition) {
  return {
    readColumns: definition.readColumns || definition.writeColumns,
    hashColumns: definition.hashColumns || definition.writeColumns,
    ...definition,
  };
}

export const runtimeMetadataConfig = {
  table: "runtime_metadata",
  primaryKey: "snapshot_key",
  writeColumns: [
    "snapshot_key",
    "generated_at",
    "updated_at",
    "source",
  ],
};

// 每个条目都把一个运行时集合映射到物理表，包括主键和 JSON 列。
export const stateTableConfigs = [
  config({
    stateKey: "documentSources",
    table: "document_source",
    primaryKey: "source_id",
    writeColumns: [
      "source_id",
      "source_type",
      "subject",
      "owner_id",
      "import_batch_id",
      "metadata_json",
      "created_at",
    ],
  }),
  config({
    stateKey: "documents",
    table: "document",
    primaryKey: "document_id",
    writeColumns: [
      "document_id",
      "source_id",
      "subject",
      "stage",
      "grade",
      "season",
      "doc_role",
      "title",
      "storage_uri",
      "checksum",
      "page_count",
      "status",
      "metadata_json",
      "created_at",
      "updated_at",
    ],
  }),
  config({
    stateKey: "documentGroups",
    table: "document_group",
    primaryKey: "document_group_id",
    writeColumns: [
      "document_group_id",
      "subject",
      "group_type",
      "label",
      "status",
      "metadata_json",
      "created_at",
    ],
  }),
  config({
    stateKey: "documentGroupMembers",
    table: "document_group_member",
    primaryKey: "document_group_member_id",
    writeColumns: [
      "document_group_member_id",
      "document_group_id",
      "document_id",
      "member_role",
      "sort_index",
      "created_at",
    ],
  }),
  config({
    stateKey: "documentRelations",
    table: "document_relation",
    primaryKey: "document_relation_id",
    writeColumns: [
      "document_relation_id",
      "from_document_id",
      "to_document_id",
      "relation_type",
      "metadata_json",
      "created_at",
    ],
  }),
  config({
    stateKey: "runs",
    table: "run",
    primaryKey: "run_id",
    writeColumns: [
      "run_id",
      "run_type",
      "root_target_type",
      "root_target_id",
      "subject",
      "lane",
      "status",
      "triggered_by",
      "started_at",
      "finished_at",
    ],
  }),
  config({
    stateKey: "jobs",
    table: "job",
    primaryKey: "job_id",
    writeColumns: [
      "job_id",
      "run_id",
      "job_type",
      "lane",
      "capability",
      "resource_class",
      "priority",
      "idempotency_key",
      "status",
      "attempt_count",
      "max_attempts",
      "lease_expires_at",
      "heartbeat_at",
      "timeout_at",
      "cancel_requested_at",
      "next_retry_at",
      "error_code",
      "error_detail_ref",
      "payload_ref",
      "result_artifact_id",
      "created_at",
      "updated_at",
    ],
  }),
  config({
    stateKey: "jobAttempts",
    table: "job_attempt",
    primaryKey: "job_attempt_id",
    writeColumns: [
      "job_attempt_id",
      "job_id",
      "attempt_no",
      "started_at",
      "heartbeat_at",
      "finished_at",
      "status",
      "error_detail_json",
      "worker_ref",
    ],
  }),
  config({
    stateKey: "jobDependencies",
    table: "job_dependency",
    primaryKey: "job_dependency_id",
    writeColumns: [
      "job_dependency_id",
      "upstream_job_id",
      "downstream_job_id",
      "dependency_type",
      "created_at",
    ],
  }),
  config({
    stateKey: "outboxEvents",
    table: "outbox_event",
    primaryKey: "outbox_event_id",
    writeColumns: [
      "outbox_event_id",
      "aggregate_type",
      "aggregate_id",
      "event_type",
      "payload_json",
      "status",
      "created_at",
      "dispatched_at",
    ],
  }),
  config({
    stateKey: "imports",
    table: "lesson_import",
    primaryKey: "import_id",
    writeColumns: [
      "import_id",
      "bundle_id",
      "content_hash",
      "lesson_id",
      "lesson_revision_id",
      "run_id",
      "review_task_id",
      "artifact_id",
      "created_at",
    ],
  }),
  config({
    stateKey: "artifacts",
    table: "artifact",
    primaryKey: "artifact_id",
    writeColumns: [
      "artifact_id",
      "run_id",
      "job_id",
      "artifact_type",
      "schema_version",
      "producer_name",
      "producer_version",
      "model_version",
      "prompt_hash",
      "plugin_version",
      "storage_uri",
      "content_hash",
      "summary_json",
      "supersedes_artifact_id",
      "integrity_status",
      "logical_status",
      "lifecycle_status",
      "created_at",
    ],
  }),
  config({
    stateKey: "artifactDependencies",
    table: "artifact_dependency",
    primaryKey: "artifact_dependency_id",
    writeColumns: [
      "artifact_dependency_id",
      "parent_artifact_id",
      "child_artifact_id",
      "dependency_type",
      "created_at",
    ],
  }),
  config({
    stateKey: "lessons",
    table: "lesson",
    primaryKey: "lesson_id",
    writeColumns: [
      "lesson_id",
      "document_group_id",
      "subject",
      "stage",
      "grade",
      "season",
      "title",
      "active_revision_id",
      "published_revision_id",
      "status",
      "created_at",
      "updated_at",
    ],
  }),
  config({
    stateKey: "lessonRevisions",
    table: "lesson_revision",
    primaryKey: "lesson_revision_id",
    writeColumns: [
      "lesson_revision_id",
      "lesson_id",
      "base_artifact_id",
      "generated_snapshot_ref",
      "manual_patch_ref",
      "merged_snapshot_ref",
      "revision_no",
      "status",
      "approval_status",
      "bundle_jsonb",
      "content_hash",
      "created_by",
      "created_at",
    ],
  }),
  config({
    stateKey: "taskProjections",
    table: "task_projection",
    primaryKey: "task_projection_id",
    writeColumns: [
      "task_projection_id",
      "lesson_id",
      "lesson_revision_id",
      "local_task_id",
      "source_node_local_id",
      "subject",
      "grade",
      "question_type",
      "stem",
      "answer",
      "explanation",
      "difficulty_level",
      "difficulty_scheme",
      "difficulty_source",
      "difficulty_confidence",
      "checkpoint_codes",
      "subject_tags",
      "source_refs_json",
      "content_hash",
      "search_text",
      "created_at",
    ],
    // `search_vector` is database-generated and should hydrate back into state,
    // but business writes must continue to source it from `search_text`.
    readColumns: [
      "task_projection_id",
      "lesson_id",
      "lesson_revision_id",
      "local_task_id",
      "source_node_local_id",
      "subject",
      "grade",
      "question_type",
      "stem",
      "answer",
      "explanation",
      "difficulty_level",
      "difficulty_scheme",
      "difficulty_source",
      "difficulty_confidence",
      "checkpoint_codes",
      "subject_tags",
      "source_refs_json",
      "content_hash",
      "search_text",
      "search_vector",
      "created_at",
    ],
  }),
  config({
    stateKey: "questionBankItems",
    table: "question_bank_item",
    primaryKey: "question_bank_item_id",
    writeColumns: [
      "question_bank_item_id",
      "subject",
      "grade",
      "current_revision_id",
      "status",
      "created_at",
      "updated_at",
    ],
  }),
  config({
    stateKey: "questionBankItemRevisions",
    table: "question_bank_item_revision",
    primaryKey: "question_bank_item_revision_id",
    writeColumns: [
      "question_bank_item_revision_id",
      "question_bank_item_id",
      "stem",
      "answer",
      "explanation",
      "question_type",
      "difficulty_level",
      "difficulty_scheme",
      "difficulty_source",
      "difficulty_confidence",
      "checkpoint_codes",
      "subject_tags",
      "source_refs_json",
      "content_hash",
      "search_text",
      "created_at",
      "created_by",
    ],
    readColumns: [
      "question_bank_item_revision_id",
      "question_bank_item_id",
      "stem",
      "answer",
      "explanation",
      "question_type",
      "difficulty_level",
      "difficulty_scheme",
      "difficulty_source",
      "difficulty_confidence",
      "checkpoint_codes",
      "subject_tags",
      "source_refs_json",
      "content_hash",
      "search_text",
      "search_vector",
      "created_at",
      "created_by",
    ],
  }),
  config({
    stateKey: "questionBankSourceLinks",
    table: "question_bank_source_link",
    primaryKey: "question_bank_source_link_id",
    writeColumns: [
      "question_bank_source_link_id",
      "question_bank_item_revision_id",
      "lesson_id",
      "lesson_revision_id",
      "local_task_id",
      "source_node_local_id",
      "source_refs_json",
      "created_at",
    ],
  }),
  config({
    stateKey: "publications",
    table: "publication",
    primaryKey: "publication_id",
    writeColumns: [
      "publication_id",
      "lesson_id",
      "lesson_revision_id",
      "status",
      "published_artifact_id",
      "material_build_id",
      "created_by",
      "created_at",
      "published_at",
      "revoked_at",
      "superseded_by_publication_id",
    ],
  }),
  config({
    stateKey: "materialBuilds",
    table: "material_build",
    primaryKey: "material_build_id",
    writeColumns: [
      "material_build_id",
      "lesson_id",
      "teacher_name",
      "build_name",
      "section_schema",
      "target_variant",
      "status",
      "created_by",
      "created_at",
      "updated_at",
    ],
  }),
  config({
    stateKey: "materialItems",
    table: "material_item",
    primaryKey: "material_item_id",
    writeColumns: [
      "material_item_id",
      "material_build_id",
      "question_bank_item_revision_id",
      "section_key",
      "placement_role",
      "target_variant",
      "sort_index",
      "difficulty_override",
      "include_answer",
      "include_explanation",
      "layout_hint_json",
      "created_at",
    ],
  }),
  config({
    stateKey: "pageAssets",
    table: "page_asset",
    primaryKey: "page_asset_id",
    writeColumns: [
      "page_asset_id",
      "document_id",
      "page_no",
      "width",
      "height",
      "image_artifact_id",
      "ocr_artifact_id",
      "layout_artifact_id",
      "status",
      "created_at",
    ],
  }),
  config({
    stateKey: "components",
    table: "component",
    primaryKey: "component_id",
    writeColumns: [
      "component_id",
      "page_asset_id",
      "parent_component_id",
      "component_type",
      "bbox_json",
      "reading_order",
      "crop_artifact_id",
      "content_hash",
      "schema_version",
      "extraction_confidence",
      "status",
      "current_revision_id",
      "created_at",
    ],
  }),
  config({
    stateKey: "componentRevisions",
    table: "component_revision",
    primaryKey: "component_revision_id",
    writeColumns: [
      "component_revision_id",
      "component_id",
      "source_task_revision_id",
      "page_no",
      "bbox_json",
      "extracted_text",
      "source_refs_json",
      "created_by",
      "created_at",
    ],
  }),
  config({
    stateKey: "componentPatchCandidates",
    table: "component_patch_candidate",
    primaryKey: "component_patch_candidate_id",
    writeColumns: [
      "component_patch_candidate_id",
      "component_id",
      "base_component_revision_id",
      "proposed_component_revision_id",
      "target_task_revision_id",
      "run_id",
      "status",
      "diff_json",
      "created_at",
      "updated_at",
      "reviewed_by",
      "accepted_lesson_revision_id",
    ],
  }),
  config({
    stateKey: "componentLinks",
    table: "component_link",
    primaryKey: "component_link_id",
    writeColumns: [
      "component_link_id",
      "component_id",
      "target_type",
      "target_revision_id",
      "relation_type",
      "created_at",
    ],
  }),
  config({
    stateKey: "sourceNodes",
    table: "source_node",
    primaryKey: "source_node_id",
    writeColumns: [
      "source_node_id",
      "lesson_id",
      "stable_code",
      "current_revision_id",
      "created_at",
    ],
  }),
  config({
    stateKey: "sourceNodeRevisions",
    table: "source_node_revision",
    primaryKey: "source_node_revision_id",
    writeColumns: [
      "source_node_revision_id",
      "source_node_id",
      "lesson_revision_id",
      "parent_node_revision_id",
      "node_type",
      "phase",
      "title",
      "order_index",
      "page_span",
      "component_bundle_ref",
      "generated_data_ref",
      "manual_patch_ref",
      "merged_data_ref",
      "status",
      "created_at",
    ],
  }),
  config({
    stateKey: "tasks",
    table: "task",
    primaryKey: "task_id",
    writeColumns: [
      "task_id",
      "lesson_id",
      "stable_question_no",
      "current_revision_id",
      "created_at",
    ],
  }),
  config({
    stateKey: "taskRevisions",
    table: "task_revision",
    primaryKey: "task_revision_id",
    writeColumns: [
      "task_revision_id",
      "task_id",
      "lesson_revision_id",
      "source_node_revision_id",
      "student_stem",
      "teacher_stem",
      "answer",
      "explanation",
      "visibility",
      "generated_data_ref",
      "manual_patch_ref",
      "merged_data_ref",
      "status",
      "created_at",
    ],
  }),
  config({
    stateKey: "checkpointCatalogs",
    table: "checkpoint_catalog",
    primaryKey: "catalog_id",
    writeColumns: [
      "catalog_id",
      "key",
      "subject",
      "scope_type",
      "status",
      "created_at",
    ],
  }),
  config({
    stateKey: "checkpointCatalogVersions",
    table: "checkpoint_catalog_version",
    primaryKey: "catalog_version_id",
    writeColumns: [
      "catalog_version_id",
      "catalog_id",
      "version_no",
      "status",
      "base_version_id",
      "overlay_ref",
      "published_at",
      "created_at",
    ],
  }),
  config({
    stateKey: "checkpointNodes",
    table: "checkpoint_node",
    primaryKey: "checkpoint_node_id",
    writeColumns: [
      "checkpoint_node_id",
      "catalog_version_id",
      "parent_id",
      "code",
      "name",
      "node_kind",
      "order_index",
      "created_at",
    ],
  }),
  config({
    stateKey: "sourceNodeCheckpointLinks",
    table: "source_node_checkpoint_link",
    primaryKey: "link_id",
    writeColumns: [
      "link_id",
      "source_node_revision_id",
      "checkpoint_node_id",
      "relation_type",
      "confidence",
      "mapping_source",
      "created_at",
    ],
  }),
  config({
    stateKey: "taskCheckpointOverrides",
    table: "task_checkpoint_override",
    primaryKey: "override_id",
    writeColumns: [
      "override_id",
      "task_revision_id",
      "checkpoint_node_id",
      "relation_type",
      "confidence",
      "mapping_source",
      "reason",
      "created_at",
    ],
  }),
  config({
    stateKey: "taskSubjectExt",
    table: "task_subject_ext",
    primaryKey: "task_revision_id",
    writeColumns: [
      "task_revision_id",
      "subject",
      "plugin_id",
      "plugin_version",
      "schema_version",
      "payload_json",
      "risk_flags",
      "created_at",
      "updated_at",
    ],
  }),
  config({
    stateKey: "reviewTasks",
    table: "review_task",
    primaryKey: "review_task_id",
    writeColumns: [
      "review_task_id",
      "target_type",
      "target_revision_id",
      "run_id",
      "status",
      "assigned_to",
      "requested_by",
      "changes_summary",
      "created_at",
      "updated_at",
    ],
  }),
  config({
    stateKey: "qualityEvaluations",
    table: "quality_evaluation",
    primaryKey: "quality_evaluation_id",
    writeColumns: [
      "quality_evaluation_id",
      "target_type",
      "target_revision_id",
      "rule_set_version",
      "check_code",
      "severity",
      "score",
      "passed",
      "evidence_ref",
      "evaluated_at",
    ],
  }),
];

export const stateTableConfigMap = new Map(
  stateTableConfigs.map((definition) => [definition.stateKey, definition])
);
